In [1]:
import mxnet as mx

E:\Anaconda\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
E:\Anaconda\lib\site-packages\h5py\tests\old\test_attrs_data.py:251: DeprecationWarning: invalid escape sequence \H
  s = b"Hello\x00\Hello"


In [2]:
a = mx.nd.ones((2,3))

In [3]:
b = a*2+1

In [4]:
b.asnumpy()

array([[3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [5]:
import numpy as np

In [6]:
A_np = np.array([[0,1,2,3,4],[5,6,7,8,9]])

In [7]:
import mxnet.ndarray as nd

In [8]:
A_nd = nd.array(A_np)

In [9]:
A_nd


[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
<NDArray 2x5 @cpu(0)>

In [10]:
A2_np = A_nd.asnumpy()

In [11]:
A2_np

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]], dtype=float32)

In [12]:
X = mx.nd.array([[1,2],[3,4]])

In [13]:
Y = mx.nd.array([[5,6],[7,8]])

In [14]:
result = X + Y

In [15]:
result


[[ 6.  8.]
 [10. 12.]]
<NDArray 2x2 @cpu(0)>

In [16]:
a = mx.sym.Variable('a')

In [17]:
b = mx.sym.Variable('b')

In [18]:
c = a + b

In [19]:
executor = c.bind(mx.cpu(),{'a':X,'b':Y})

In [20]:
result = executor.forward()

In [21]:
result

[
 [[ 6.  8.]
  [10. 12.]]
 <NDArray 2x2 @cpu(0)>]